[package]
name = "united_traders"
version = "0.1.0"
authors = ["Dmitry Novikov <novikov.dm.al@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
